import re
import json

raw_prompt_text = """## 1. THE TRANSFORMATIVE POWER OF "HELLO" | DIANE CARTER | TEDXGARY

My father and I were a dynamic duo. He taught me to tell time, fix a flat tire, and understand baseball. When he had knee surgery, I came home to care for him, and a few weeks became months. Once I finally returned to work, as a director for an after-school program, I worried less about the job than about connecting with the children. On my first day, facing seventy-five kids, I noticed a little girl sitting alone at one end of a lunch table. I walked over and said, "Hello." Her eyes lit up, as if to ask, "You see me?" She transformed before me, sitting upright like a wilted flower blooming again. That taught me a greeting is an invitation to shared humanity. I grew up in a small Mississippi town where speaking to everyone, regardless of background, was expected, not optional. My grandmother, Rosa Whitfield, always said, "Be sweet and speak to people." But the pandemic changed me. Masked and distanced, I stopped greeting strangers. I had to relearn what Rosa taught me. Research confirms what I felt: greeting strangers reduces loneliness, which the World Health Organization calls as damaging as smoking fifteen cigarettes a day, and boosts mood and connection. A simple hello ripples outward, lifting both giver and receiver. So don't say goodbye to hello. Use it to make the world a little brighter, one greeting at a time.

## 2. HUMAN SCIENCES: SAYING HELLO IS A RADICAL ACT | MEERA ANAND | TEDXDIA YOUTH

Studies suggest most people lean extroverted, yet many of us quietly avoid conversations with people outside our circle. I once caught myself judging names on a group call without ever having spoken to those people, and it troubled me. Our sense of identity comes from the Latin word for "sameness," meaning it is shaped by how we relate to others, not just our individuality. We often hide the parts of ourselves that feel too unusual to fit in, then protect a narrow, curated identity, reinforced by social media, where people become categories rather than full human beings. This shrinks real connection: roughly one in six people now experience clinical loneliness. Without realizing it, we develop implicit bias, quietly excluding people who seem unlike us. Social exclusion can raise depression rates by up to 40 percent and shorten lifespan by years, comparable to heavy smoking. Yet diverse interaction sharpens us: studies show ethnically diverse groups see meaningful gains in innovation and problem-solving, and reduced belief in misinformation. History's greatest breakthroughs, from relativity to the blood bank to climate activism, came from people different from one another. My best friend once climbed out of a depressive episode after a single conversation with a stranger. That is why saying hello is radical. Reach out to someone new today; the world is only as big as you're willing to notice.

## 3. CURIOSITY - THE POWER OF ASKING QUESTIONS | NADIA FLORES | TEDXNORMAL COMMUNITY HS

A single question can redirect a conversation and even reshape how we see the world. One day, exhausted during a study break, I asked a friend, "Is a brownie a type of cookie?" What followed was a spirited, evidence-based debate that ended in laughter, but it stuck with me because it sparked curiosity, communication, and connection from one unassuming question. Curiosity is the backbone of society, driving every "what if" behind innovation. Neurologically, the frontal lobe and cerebral cortex handle the higher thinking involved in forming questions, while the limbic system fuels our natural interest, translating curiosity into language. Beyond biology, questions build relationships: showing genuine interest in someone's perspective creates trust and understanding. Curiosity also turns inward, prompting us to examine our own motivations and fears. Yet many people avoid asking questions, worried about looking foolish. To make curiosity feel safer, keep questions clear and focused, ask one at a time, and let genuine interest guide you rather than judgment. Curiosity isn't weakness, it's courage: it takes bravery to admit what you don't know, confidence to challenge assumptions, and humility to truly listen. So the next time you're in a meeting, classroom, or casual conversation, ask the small question, the risky one, the one that might spark debate. Learning to stay curious may be the most powerful tool we have.

## 4. HOW TO ASK FOR HELP -- AND GET A "YES" | DR. NORA ELLISON

Asking for help feels uncomfortable, so most people avoid it, even when they need it constantly. My own father once refused to stop and ask directions during a family road trip, insisting we weren't lost. Research shows people often fall for the "illusion of transparency," wrongly assuming others can sense their needs. In truth, roughly 90 percent of workplace help happens only after someone explicitly asks. To improve your odds of getting a "yes," follow a few principles. First, be specific about what you need and why; vague requests, like a stranger's "let's connect" message, rarely get a response. Second, avoid disclaimers, apologies, or bribes when asking; over-apologizing makes helpers uncomfortable, and offering payment to friends can turn a relationship into a transaction, making people less willing to help. Third, ask in person rather than by email or text; face-to-face requests are about 30 times more likely to succeed, since it's easier to say no from a distance. Finally, and most overlooked, follow up afterward. People find helping rewarding only when they know their help actually mattered, which is why effective charities like classroom-donation platforms send photos and updates from recipients. Tell your colleague their advice helped you land the sale, or your partner that their support carried you through a hard time. Nobody succeeds alone, so ask for help out loud, clearly, and in a way that lets the helper feel the impact they made.

## 5. DO YOU TALK TO YOURSELF? HERE'S HOW TO HARNESS YOUR INNER VOICE | DR. MARCUS ADLER | TED

I am a psychologist who has spent twenty-five years studying how people manage emotions, particularly the voice inside our heads. We spend between a third and a half of our waking hours not focused on the present, often talking to ourselves. This inner voice helps us hold information in mind, rehearse difficult conversations, motivate ourselves, and make sense of challenges. But it can also misfire into "chatter," negative thought loops and self-criticism that hurt our thinking, our relationships, and even our physical health by prolonging stress and increasing risks like cardiovascular disease. Rather than silencing this voice, we should learn to harness it. One tool is "distanced self-talk": coaching yourself by name, in the second person, the way activist Amara Nolan did when facing danger, saying "Amara, what would you do?" This shifts perspective and makes advice easier to accept. A second tool is choosing the right people to talk to; venting alone doesn't resolve chatter, but conversations that validate feelings and then broaden perspective do. The third tool is awe, the emotion sparked by encountering something vast, like a sunset or images from Mars, which shrinks our sense of self and, with it, our chatter. Compared to ancient remedies like skull-drilling or lobotomies, our modern science-based tools are remarkable. Now we must use them, and teach ourselves to communicate with ourselves as skillfully as we do with others.

## 6. DARE TO DISAGREE | HELEN MARSTON

In 1950s Oxford, physician Vivian Sterling was a rare woman in medicine who researched why childhood cancer, unlike most diseases, struck affluent families. With minimal funding, she surveyed everything imaginable and found one striking pattern: children who died were twice as likely to have mothers X-rayed during pregnancy. Though she published in 1956, it took twenty-five years for medical authorities to stop X-raying pregnant women, proving that open data alone doesn't drive change. Vivian's confidence came from her statistician partner, Walter Combs, whose entire job was to try to disprove her, creating constructive conflict rather than agreement. That kind of thinking partnership requires seeking out people unlike ourselves, being willing to change our minds, and treating disagreement as a form of care rather than hostility. Organizations struggle with this: surveys show 85 percent of executives admit to sitting on workplace concerns they're afraid to raise. One engineer, Joseph, worried his company's medical device was too complex and risky, but stayed silent for fear of looking foolish. When he finally spoke up, he found colleagues shared his doubts, and together they improved the design. He'd feared being seen as a troublemaker; instead, he became a leader. The biggest disasters rarely stem from hidden information, but from data we're willfully blind to because we fear the conflict it provokes. Openness alone isn't enough. We need the courage and skill to argue well, together.

## 7. 5 STEPS TO DESIGNING THE LIFE YOU WANT | DR. ALAN REYES | TEDXSTANFORD

I teach design thinking, developed with my co-author Peter Lang at Stanford's Life Design Lab, applying the mindsets designers use, curiosity, reframing, collaboration, awareness of process, and bias toward action, to designing a life rather than a product. We noticed people get "stuck" because of dysfunctional beliefs: that everyone has one true passion (fewer than 20 percent of people do), that there's a deadline for figuring life out, or that there's a single "best" version of yourself to become. In reality, life design works through five ideas. First, connect the dots between who you are, what you believe, and what you do, since coherence between these creates meaning. Second, avoid "gravity problems," circumstances you can't fix, and reframe them into something workable. Third, always generate three possible life plans rather than committing to one, and prototype ideas through small real-world experiments rather than only imagining them. Fourth, cultivate "luck" by paying attention: research shows people who see themselves as lucky notice unexpected opportunities in their peripheral vision far more often. Fifth, once you narrow your options to around five, choose with both reason and gut feeling, since decisions made emotionally as well as rationally tend to satisfy us more. Finally, commit to your choice and let go; studies show reversible decisions make people less happy than final ones. Get curious, talk to people, try things, and you can design a joyful, well-lived life.

## 8. THE MAGIC WASHING MACHINE | LARS ANDERSSON

I was four years old when my mother loaded a washing machine for the first time, a purchase my parents had saved years for. My grandmother, who had hand-washed laundry for seven children over a fire, watched the entire cycle, mesmerized, calling it a miracle. Today, wealthy countries fill their homes with machines, while two billion people still live on less than two dollars a day and wash entirely by hand, a task that consumes hours every week, mostly for women. When I ask environmentally conscious students whether everyone can have washing machines, they hesitate, yet none of them hand-wash their own jeans. Analyzing global energy use, I found the richest billion people consume half the world's energy, while billions more use very little. By 2050, population growth among the poorest and economic growth among emerging "New East" economies will roughly double global energy consumption, and the richest will still use the most. The real challenge is for wealthier nations to become more efficient and produce far more green energy before lecturing others. Meanwhile, a woman in a Rio favela who finally got electricity was so grateful to her energy minister that she voted her into the presidency; where democracy exists, people vote for washing machines. My own mother loved hers not for the chore it removed but for what it gave her: time. She used it to read to me and to study English herself. Thank you, industrialization, for giving us time to read.

## 9. HOW TO RECLAIM YOUR LIFE FROM WORK | DANIEL PRESTON | TED

I once met a man at a hostel who was baffled when I asked, "What do you do?" as if I'd asked something deeply personal. In the US, that question is often our first, revealing how tightly we conflate identity with occupation. As a labor journalist who interviewed over a hundred people for my book on work and identity, I once asked my favorite poet, Owen Marsh, how he felt about "doing what you love." He told me some people do what they love for work, others work so they can do what they love outside of it, and neither is more noble. Roughly 48 percent of workers globally report burnout, yet a week's vacation rarely fixes it, because the real problem is how narrowly we've built our identities around our jobs. The fix is diversifying our sense of self, the way an investor diversifies a portfolio. First, create "time sanctuaries," protected spaces where work isn't allowed, whether learning a language or playing with your kids phone-free. Second, fill that time with small, genuine activities tied to other identities you value, a weekly walk, ten minutes of piano. Third, join communities that don't care what you do for work; my weekly basketball game reminds me I exist for more than economic output. A diversified identity makes us more creative, more resilient to job loss, and better people, not just better workers. So instead of asking "What do you do?" try asking, "What do you like to do?"

## 10. THE HAPPY SECRET TO BETTER WORK | GREG DONOVAN

When I was seven, my five-year-old sister Amy fell off the top bunk during a pretend battle. To stop her crying before she woke our parents, I told her no human lands on all fours like that, so she must be a unicorn. She scrambled back up, delighted. That childhood trick previewed positive psychology, the field I've studied ever since. Traditional science trains us to discard outliers and study the average, but averages just make us average. Positive psychology instead studies why some people rise far above the curve, so we can raise everyone's baseline. Most news is negative, which skews our sense of reality, but if I know everything about someone's external circumstances, I can predict only 10 percent of their long-term happiness; the other 90 percent depends on how the brain processes the world. Only 25 percent of job success is predicted by IQ; the rest comes from optimism, social support, and seeing stress as a challenge rather than a threat. Most of us assume success brings happiness, but success's goalposts keep moving, so happiness never arrives. It actually works the other way: a positive brain is measurably more productive, creative, and accurate at tasks, including medical diagnoses and sales. Simple daily habits, writing three gratitudes, journaling a positive experience, exercise, meditation, and one act of kindness, can rewire the brain toward positivity within twenty-one days, reversing the formula for happiness and success.

## 11. DO SCHOOLS KILL CREATIVITY? | DR. WILLIAM ROBERTS | TED

Everybody has an interest in education, yet no one can predict the future they're meant to be preparing children for. Despite this uncertainty, one thing is clear: children have extraordinary creative capacities that schools tend to squander. Creativity deserves the same status as literacy. Kids are unafraid to be wrong, and if you're not prepared to be wrong, you'll never produce anything original; yet by adulthood, most have lost that willingness, partly because schools and companies stigmatize mistakes. Picasso once observed that all children are born artists, and the challenge is remaining one as we grow up. Every education system on earth ranks subjects the same way, math and languages at the top, arts at the bottom, largely because public schooling was built to serve industrial-era jobs and university admission, not the diversity of human talent. Intelligence is diverse, dynamic, and distinct, not a single fixed academic ability. Choreographer Diane Lynwood, dismissed as a disruptive child with a possible learning disorder in the 1930s, was recognized by a doctor as simply needing to move to think; she went on to a celebrated career in dance and musical theatre. Countless people like her are told their talents don't count. As more people worldwide graduate than ever before, and degrees lose value amid rapid technological change, we must radically rethink education, treating creativity as the rich resource it is, so children can build a future we may never see ourselves.

## 12. EVERY KID NEEDS A CHAMPION | MS. CAROL BENSON | TED

I've spent my life around education, following in the footsteps of educator parents and grandparents. We know poverty, absenteeism, and negative peer influence explain why kids struggle, but we rarely talk about the value of human connection. As one researcher put it, no significant learning happens without a significant relationship. A colleague once told me she wasn't paid to like her students, only to teach them; I warned her it would be a long, hard year, and it was. Simple acts matter: apologizing to a student when you're wrong shocks and disarms them in a good way. Facing an academically struggling class one year, I told them they'd been placed together because they were the best, and had me as their teacher, so we'd prove it to everyone else. I gave them an affirmation to repeat daily: "I am somebody, I am powerful, I deserve this education." Repeated often enough, it becomes part of who you are. When a student who got eighteen questions wrong on a quiz saw a smiley face beside his grade, he asked why; I told him he'd gotten two right, he wasn't all bad, and he could do better next time. A negative score crushes a child's spirit; a small positive note lifts it. This work is exhausting and often thankless, but every child deserves a champion: an adult who never gives up on them and insists they become the best they can be. We can do this. We were born to make a difference.

## 13. WHAT IS A COLLEGE EDUCATION? | PROFESSOR DANIEL WRAY AT TEDXOU

I want to raise three uncomfortable questions: what is a college education, what percentage of people are capable of one, and does everyone who's capable actually need one? A college education used to mean a defined four-year experience centered on independent scholarship, aimed at a small elite; only about 2 percent of young people attended in 1920. After World War II, the GI Bill and sustained prosperity expanded access to roughly half of each age group. Since then, political, economic, social, and cultural shifts have upended that model. States have slashed university funding, forcing tuition far above inflation while median family income has actually declined, pushing students into heavy debt. Job recoveries after recent recessions have been painfully slow and "jobless," and the jobs now being created are often lower-skill than the ones lost. In 2012, 53 percent of recent graduates were unemployed or underemployed. Meanwhile, students study roughly half as much as they did in the 1960s, and employers increasingly complain that graduates can't write well. Massive open online courses, championed by innovators like Nathan Kessler of a popular online academy and Sebastian Krohn's early experiment in free online courses, seemed promising, but roughly 90 percent of enrollees never finish; they help only the already motivated. My proposal: everyone must work harder, students, faculty, and administrators alike, universities should be run as universities, not businesses, and students are students, not customers.

## 14. WHY YOU HAVE TO FAIL TO HAVE A GREAT CAREER | KEVIN MARSH AT TEDXUW

Failure is something everyone dreads and everyone eventually experiences, academically and professionally. This builds on a well-known talk that argued you will fail to have a great career "unless," leaving the "unless" for the audience to figure out. An optical illusion exercise, where most people wrongly assume two lines are equal length simply because they were warned about a trick, showed how fear of being wrong makes us silence our instincts, and that silence is itself a kind of failure. In my second year of university, my brother and I started a biodiesel company, hauling a sample jar to a transit authority to pitch investors. On a bitterly cold day, the biodiesel froze solid in my glove compartment; I spent a tense elevator ride trying to thaw it under a hand dryer and a heating vent, only for it to arrive as slush in front of the clients. The company failed, and I failed a term of school in the same period, watching friends move ahead while I started over at an entry-level coding job. That collapse, however, taught me more than success would have. The real lesson isn't "you will fail unless you avoid failure," it's that failure itself is often the path forward. Don't let fear of what friends, parents, or institutions think stop you from speaking up or trying. Failing that term and failing to build that company turned out to be the best things that ever happened to me.

## 15. HOW DO WE HEAL MEDICINE? | DR. OWEN WHITFIELD

I began my career as a surgical trainee wondering how anyone gets good at a skill that demands so much. In the 1930s, medicine was simple enough that a single doctor with a prescription pad and a nurse could handle nearly everything a patient needed; autonomy was the highest value. Today we've discovered thousands of drugs and procedures, and a typical hospital patient may see more than fifteen clinicians, yet we still train people as independent "cowboys" rather than coordinated "pit crews." The result: many patients with common conditions like heart disease, asthma, or stroke receive incomplete care, and two million people pick up hospital infections from lapses in basic hygiene. Complexity, not corruption, drives rising costs, and remarkably, the best-performing care is often the least expensive, because true systems, not just excellent individual components, produce the best outcomes. Building an effective system requires three skills: recognizing failure through unglamorous data, as one surgeon discovered after tracking an unexpectedly high number of CT scans in his community; devising practical solutions, like the nineteen-item surgical checklist my team developed with an aviation engineer, which cut complications by 35 percent and deaths by 47 percent across hospitals worldwide; and implementing these tools despite resistance, since they demand humility over independence. Even real cattle ranchers now coordinate with protocols and checklists. Making systems work, in medicine and beyond, is the defining task of our generation.

## 16. WHAT DOCTORS DON'T KNOW ABOUT THE DRUGS THEY PRESCRIBE | DR. HELENA MOSS

As a doctor who has spent a decade examining how medical treatments are evaluated, I've found that the evidence guiding life-and-death decisions is fundamentally compromised. The problem is publication bias: pharmaceutical companies that fund trials showing positive results publish them in prestigious journals, while unfavorable results are often quietly shelved. I once prescribed an antidepressant based on published literature showing it was safe and effective, unaware that six of seven trials conducted on it actually showed no benefit over a placebo and worse side effects; only the one positive trial had been published. A landmark 2008 study of antidepressant trials registered with regulators found that while nearly all published trials appeared positive, in reality only about half of all trials conducted showed positive results. This selective reporting is legal, yet it amounts to hiding every coin flip that lands on tails and presenting only the heads. The consequences are severe: governments spent billions stockpiling an anti-flu drug based on incomplete data, only for independent researchers to later find no solid evidence it prevented hospitalization. The fix is straightforward, if politically resisted: require every clinical trial to be registered before it begins, and mandate publication of all results within a year of completion. Until that transparency is enforced, doctors cannot make fully informed decisions, and patients cannot trust that their treatment is based on the whole truth rather than a convenient fraction of it.

## 17. WE NEED TO TALK ABOUT AN INJUSTICE | MARCUS WHITFIELD | TED

I spend most of my time in jails, prisons, and low-income communities, so being here has been energizing. I learned about the power of identity from my grandmother, the daughter of enslaved parents, who once pulled me aside as a child and made me promise three things: care for my mother, always do right even when it's hard, and never drink alcohol. I've kept that promise, not because it's virtuous, but because identity shapes what we believe is possible. Today, the US incarcerates 2.3 million people, up from 300,000 in 1972, the highest rate in the world, with roughly one in three Black men aged 18 to 30 under some form of correctional control. Our justice system treats the rich and guilty better than the poor and innocent; wealth, not culpability, often determines outcomes. In Alabama, 34 percent of Black men have permanently lost the right to vote due to convictions. I once filed a motion asking the court to try my poor, fourteen-year-old Black client the way it would try a privileged, elderly white executive, and was met with outrage, but also quiet support from an elderly courthouse janitor who told me to keep my eyes on the prize. I believe each of us is more than the worst thing we've ever done, that the opposite of poverty is often justice rather than wealth, and that a society is judged not by how it treats the powerful, but by how it treats the poor and the condemned.

## 18. A DEEPER LOOK INTO OUR JUSTICE SYSTEM | PROFESSOR DANIEL KESSLER | TEDXUCINCINNATI

My client Marcus Reid walked free at 57 after serving almost 40 years for a murder he didn't commit, convicted in 1975 largely on a twelve-year-old's mistaken account. Since co-founding the Ohio Innocence Project in 2003, our work has freed 24 wrongfully convicted people who together served 450 years for crimes they didn't do, part of roughly 2,000 known exonerations nationwide, almost certainly the tip of the iceberg. I came to this work skeptical, a former prosecutor who doubted innocent people were often convicted, until DNA testing cleared a client I was sure was guilty. Three psychological failings drive most wrongful convictions. Confirmation bias leads investigators to interpret ambiguous evidence, including roughly 40 percent of forensic testimony in known wrongful convictions, in ways that confirm existing suspicions, much as people reading the same political debate see opposite winners depending on their party. Malleable memory means eyewitnesses, even fingerprint experts, can be unconsciously swayed by suggestion, and about a third of exonerees had falsely confessed after hours of interrogation involving lies about supposed DNA or fingerprint matches. Finally, our system still assumes people, including trained officers, can reliably detect lies; in reality, humans across hundreds of studies are only about 54 percent accurate, barely better than chance. My client Walter Danvers was convicted despite ignored alibi evidence and forensic clues pointing elsewhere, while the actual perpetrator, living two doors away, later confessed. We're still investigating crimes with 1950s-era assumptions about the human mind.

## 19. THE FUTURE OF TRANSPORTATION | DEREK LANGFORD | TEDXTORONTO

I've loved building things since childhood, and my research today focuses on giving people superhuman ways to sense and control their environment, but as a kid I just wanted to solve something big. Our cities are built around cars rather than people, and 94 percent of global energy still comes from non-renewable sources. Transportation is one of the largest sources of waste; a single seat on a jet flight pollutes as much as leaving a light on for half a million hours. I see three coming shifts. First, efficiency: mass transit like subways and high-speed rail moves people far more efficiently than everyone driving separately. Second, intelligence: digital systems, like early research into tracking driver perception at the University of Toronto, will increasingly guide vehicles the way a traffic controller guides planes. Third, a genuine leap in vehicle design itself. My team has been developing TransPod, an evolution of the century-old Hyperloop concept, in which pods travel through a near-vacuum tube at speeds over 1,000 km/h, eliminating the air resistance that wastes energy in cars and jets, and running entirely on electricity, including solar power, with no fuel carried onboard. Picture someone in Montreal taking a 45-minute pod ride to spend an afternoon in New York and returning home for dinner. Connecting cities at ultra-high speed could make them feel like extensions of home, narrowing the divide between financial and industrial centers. The future of transportation will be our legacy. The question is whether we choose it.

## 20. HOW PUBLIC SPACES MAKE CITIES WORK | ANNE PETTIGREW

Cities are fundamentally about people, and public spaces, more than buildings, determine whether a city truly comes alive. As an animal behaviorist turned city planner, I first studied this by observing a tiny Manhattan park built by my stepfather, where movable chairs, greenery, and the simple presence of other people made visitors linger and feel at ease, unlike the sterile, empty plazas architects and developers typically favor because they require little maintenance. My first real fight for great public space came at a barren landfill site in lower Manhattan, where we built a small, meticulously detailed public esplanade before any development, testing even the exact height of a railing so it wouldn't block the water view. Years later, as the city's planning commissioner, I faced the challenge of housing a million additional residents without adding more cars, so we rezoned 124 neighborhoods over twelve years to concentrate new development near transit, so that 90 percent of new housing now sits within a ten-minute walk of a subway. I poured that same obsessive care into transforming two miles of derelict Brooklyn waterfront and a new park in lower Manhattan into beloved public spaces. The most contested project of all was the High Line, a disused elevated railway turned garden, which developers repeatedly tried to shrink or dismantle for commercial gain. Great public spaces are never accidental and never permanently safe; they require constant, vigilant champions. A successful city, like a great party, is one people simply don't want to leave.

## 21. IS PUBLIC TRANSPORTATION THE ANSWER? | RACHEL DUNMORE | TEDXUNIVERSITYOFTULSA

Nearly every American city struggles with poverty, inequality, vacancy, and unemployment, problems too complex to solve with a single formula since, as astrophysicist Victor Kaplan famously joked, human behavior makes sociology far messier than physics. My case study of Dayton, Ohio, a Rust Belt city that lost nearly half its population after manufacturing moved south, measured urban decline against distance from the city's three major bus hubs. I found that areas within a mile of a hub, roughly the accessibility threshold for people without a car, showed no severe decline at all, while decline increased steadily farther away. This mirrors research from Portland State University linking better transit access to improved health outcomes in low-income neighborhoods. So what stands in the way? Largely, an individualistic mindset toward transportation that dates back to the early twentieth century, when automobile companies bought up popular urban trolley systems and tore out the tracks to sell more cars, eventually culminating in the Interstate Highway System. That shift made it easy to think only "how do I get there" rather than "how do we get there." Roads, cars, and highways aren't inherently the problem; we simply need to design them with everyone in mind. My findings suggest public transportation could meaningfully address poverty and urban decline, but only if we start treating mobility as the collective, public good it actually is.

## 22. HOW TO MAKE TRANSPORTATION QUIETER, CLEANER AND CHEAPER | AMARA OKONKWO | TED

I grew up fascinated by cars and engineering, and I eventually helped build one of Africa's first electric vehicles as a student at a Ugandan university, at a time when much of the world dismissed electric mobility as irrelevant to the continent. That team went on to build Africa's first plug-in hybrid and its first solar electric bus prototype, driven by the belief that Africa should help shape the future of electric mobility, not just consume it. Buses move over 60 percent of people across African cities daily, making them a prime target for electrification, yet range anxiety, high upfront costs, and limited charging infrastructure have slowed adoption everywhere. As managing director of an electric bus company operating in Kenya and Rwanda, I've watched our fleet grow to 77 buses carrying more than 30,000 passengers daily. We overcame skepticism, including doubts our buses could handle Kigali's hills, by using locally generated renewable electricity, which is cheaper and cleaner than imported diesel, designing buses around real route data, building our own charging and maintenance infrastructure, locally assembling the buses to create jobs, and offering a pay-as-you-drive leasing model so operators avoid heavy upfront loans. Because East Africa's electricity is over 90 percent renewable, each electric bus replacing a diesel one prevents up to 50 tonnes of CO2 annually, five times the impact of a similar vehicle in California. Africa doesn't need to catch up on electric mobility; it can lead it, without waiting for government subsidies.

## 23. SMART TRAVEL AND THE IMAGINATION OF FUTURE CITIES | PROFESSOR WEN LIANG | TEDXTHEBUND

More than half the world's population already lives in cities, a figure expected to reach nearly seventy percent by 2050, yet our answer to growth has largely been to build more roads, which only induces more traffic rather than relieving it. The real solution is "smart travel," a shift from owning vehicles to accessing mobility on demand through a single platform integrating buses, subways, shared bikes, and autonomous shuttles, known as Mobility as a Service. By analyzing real-time data from GPS, phone signals, and transit systems, artificial intelligence can predict congestion before it happens and reroute buses or traffic signals accordingly. In Singapore, where I've spent years researching urban mobility, a "car-lite" approach combining electronic road pricing with ensuring every resident lives within a five-minute walk of transit has reduced the practical need for private cars. Looking ahead, shared autonomous vehicle fleets that rarely need to park could free up to eighty percent of space currently devoted to parking, space that could become parks, gardens, or affordable housing. But technology must remain a means, not an end; smart travel has to serve the elderly, disabled, and underserved communities, not just the privileged. The cities we build today will shape quality of life for generations. We should aim for cities that connect people as communities rather than isolating them in metal boxes.

## 24. THE ROLE OF AUTONOMOUS TRAINS IN GLOBAL MOBILITY | SAMUEL VOGT | TEDXSTUTTGART

Traffic jams rank among the top sources of stress worldwide, a problem worsened by explosive population growth, and autonomous cars alone won't solve urban congestion. Trains, though rarely advertised the way cars are, remain among the safest and cleanest modes of transport, producing less than two percent of transport-related CO2 emissions, and a single train can replace between 250 and 2,000 cars. Automatic trains, common in closed environments like metros and airport shuttles, have existed for thirty years, but fully autonomous trains operating in open environments, where anything from stray animals to pedestrians might appear on the tracks, require far more sophisticated sensors and intelligence. Operators want autonomy chiefly to increase capacity: today's signaling only allows one train per section regardless of length, but future systems using satellites and advanced sensors could safely run trains closer together, react faster than any driver, and use predictive maintenance to catch problems like a falling tree before they cause delays. Just as photography didn't eliminate painters and 3D film didn't eliminate actors, but transformed their roles, train drivers will likely become "augmented," managing exceptions from a control office rather than a cabin. Ultimately, no single mode, autonomous car, train, or bus, solves mobility alone; the real opportunity lies in seamlessly connecting them door to door, minimizing the waiting and transferring between modes, because the goal was never just moving vehicles. It's moving people, along with their dreams and needs.

## 25. HYPERLOOP: REVOLUTIONISING THE FUTURE OF TRANSPORTATION | MARCUS WEBB | TEDXGATEWAY

Our ability to move will shape the future of humanity. As a child riding the New York subway with my father, I dreamed of driving the train; decades later, I actually ran that entire transit system, only to find that residents still thought it wasn't good enough. Later, running Hong Kong's celebrated metro, on time 99.9 percent of trips, I heard the same complaint. The real problem isn't transportation itself, it's incrementalism: legacy systems built decades ago can only be improved so much. That's why I joined an effort to build Hyperloop, the first genuinely new mass transit system in over a century, using magnetic levitation to travel near 1,000 km/h with no direct emissions and no fixed schedule. By 2050, two-thirds of the world will live in cities, and scientists warn we must halve our carbon footprint within a decade; incremental fixes won't meet problems of that scale. In the Middle East, plans call for a solar-powered system serving 45 million riders a year, built more cheaply than high-speed rail yet three times faster. A proposed Hyperloop route between Mumbai and Pune, 120 kilometers apart but currently a three-to-four-hour drive, would shrink that trip to 28 minutes, doubling ridership while cutting 150,000 tons of carbon annually. History shows what such leaps can do: trains turned days into hours, planes turned months into days. When my newborn grandson reaches his teens, I believe he'll be riding Hyperloop, inheriting a better-connected world.

## 26. WHY THE FUTURE OF COMMUTING IS FRIENDLY | ELENA MARCHETTI | TEDXNEWBEDFORD

The average commuter spends roughly seven hours a week behind the wheel, more time than most people give any hobby, yet we rarely ask whether we actually enjoy it. Stuck in traffic, we feel isolated even though every car around us holds another person losing the same seven hours, simply because we have no data connecting us to them. That's beginning to change. Since the 1970s, when the FAA centralized flight data to prevent midair collisions, air travel has enjoyed decades of transparent booking tools like Expedia. Rideshare companies later applied the same idea to taxis, bringing an offline industry online and creating "data transparency," letting riders see which cars are nearby before booking. From there, transportation has fragmented into a spectrum: car rental-style apps, minute-by-minute car sharing, true peer-to-peer sharing like a company I'll call RideTogether, where people split the cost of a trip they were already taking, and buses, both scheduled routes aggregated by services like one I'll call Roammo, and charter buses, an industry so underdigitized that my own startup has worked to bring its pricing and routes online. New crowd-sourced bus services are even asking riders in advance whether they'd choose shared transit over driving alone. All of this data is slowly revealing something we've missed: we are never really traveling alone. As this shared reality becomes visible, we can build communities of transportation, turning seven wasted hours into time that adds to our lives instead of draining them.

## 27. THE MUSLIM ON THE AIRPLANE | LAYLA HAMDAN | TEDXMILEHIGHWOMEN

I carry mints on flights because after a red-eye everyone has bad breath, and offering one is often how strangers finally ask my name instead of just seeing my hijab. My name means "hope," and depending on who's asking, I'm a waitress, a student, a poet who has performed in eight countries, an activist, and a Colorado native, yet at the airport I'm a random search, and on the news I'm reduced to words like "extremist" or "suspect." The shortest distance between two people is a story, and the fastest way to hear one is to ask someone's name instead of assigning them one based on their skin, clothing, or accent. We see this in how the term "migrant" quietly replaced "refugee" in coverage of families fleeing war, turning circumstance into choice, and in how news coverage treats violence differently depending on what the perpetrator looks like, even though acts of terrorism have historically come from every background. A hate crime in my own community took the lives of three young Muslim Americans, a newly married couple and a younger sister, people with full lives and dreams who were reduced by their killer to a single, false label before he took their lives. Yet I've also had strangers, moved simply to see a piece of my identity, offer quiet solidarity instead of suspicion. Asking someone's name is a small act that opens an entire world, ancestry, stories, survival, but it takes both courage to ask and courage to answer.

## 28. HOW MUCH DOES IT COST TO FLY PRIVATE? | MELISSA HARTWELL

Across 2023 and 2024, one internationally renowned musician took 396 private flights in a year, one lasting just six minutes, an extreme but not unheard-of pattern among wealthy frequent flyers. Renting a private jet costs roughly $7,500 an hour domestically and $17,000 internationally, meaning over $40,000 for a Los Angeles-to-New York trip and over $120,000 to cross the Atlantic, before crew, fuel, landing fees, and taxes. Buying a jet outright runs $2 to $65 million, plus up to $1 million a year in maintenance. Beyond the financial cost, the environmental toll is severe: commercial flights emit roughly one ton of CO2 per passenger, but private jets emit 10 to 20 times more per passenger due to their small passenger loads. In 2023, the top ten American private fliers alone produced more combined emissions than 6,500 average people, and roughly 1 percent of all fliers now account for nearly half of aviation emissions. One promising fix is Sustainable Aviation Fuel, made from waste oils and renewable crops rather than fossil fuels, which could cut aviation emissions by up to 94 percent if fully adopted, though it currently costs about three times as much as conventional fuel and can't yet be produced at scale. Since private jet owners already spend heavily on flights, a modest additional cost per flight to use sustainable fuel could help fund the scale-up needed to eventually make it cheaper for everyone.

## 29. HOW TO FEEL AT HOME IN THE AIRPORT | DAVID FONTAINE | TEDXEMILYCARRU

I've always wanted to travel the world, but I discovered my favorite places are actually airports, once even flying to Seattle purely to visit its terminal. We imagine travel as full of cultural novelty, yet we often crave familiar comforts once we're actually somewhere unfamiliar. Flying to India, I pictured haggling with a rickshaw driver, yet I simply took a taxi. Flying to Barcelona, I imagined sipping wine among Gaudí's architecture, yet I ordered a Diet Coke, then a second one to save for later. In unfamiliar situations, we quietly seek out the familiar: soda, tomato juice, holiday reminders, two-ply toilet paper, seatbelts, even Hollywood movies. These small comforts remind us of home, wherever we are. So don't be surprised if you, too, one day find yourself on a plane just to visit an airport.

## 30. IS AIRPORT SECURITY EFFECTIVE? | THE SCIENTIFIC BREAKDOWN

Airport security can feel tedious, but the science behind it is straightforward. Bag scanners use both low- and high-energy X-rays; denser materials absorb more low-energy rays while organic materials, often linked to explosives, appear in a distinct color, letting screeners spot suspicious items. Because the X-rays stay contained within the machine, security staff face so little radiation exposure that they aren't required to wear monitoring badges. Passengers once walked through metal detectors, which use pulsed magnetic fields to sense metal objects; today most airports instead use backscatter X-ray or millimeter wave scanners. Backscatter machines use extremely weak X-rays that only penetrate clothing, exposing passengers to far less radiation than an actual flight would, though the technology is banned in many countries. Millimeter wave scanners, the cylindrical booths now more common, use non-ionizing microwaves that can't damage DNA while still revealing concealed objects through clothing. If a bag raises concern, officers may swab hands, shoes, or luggage and run the sample through an Explosives Trace Detection machine, which electrically charges the collected molecules and identifies compounds based on how long they take to travel through a tube, a process called ion mobility spectrometry. It may be tedious, but each step exists to catch real threats with minimal risk to travelers.

## 31. INSIDE THE SECRET SHIPPING INDUSTRY | JULIA WESTBROOK

Harvard Business School once named Somali piracy its best business model of the year, around the same time I learned that 544 seafarers were being held hostage on ships near the Somali coast, a scale of captivity unimaginable in any other industry. That discovery led me to a bigger surprise: shipping carries 90 percent of world trade and has quadrupled since 1970, yet remains largely invisible to the public, a condition one British admiral called "sea blindness." A well-known shipping company earns nearly as much as a major software giant, yet almost no one recognizes its name. To confront my own blindness, I sailed five weeks aboard a container ship from England to Singapore, crewed by just 21 people from half a dozen countries, thanks to automation and "flags of convenience" that let ships register under nations with no coastline at all. Passing through pirate waters, the mood shifted sharply, deck access was restricted and watches doubled, a stark reminder of the hostage crisis I'd first read about. Shipping runs on cheap, dirty bunker fuel, and while it's the greenest transport method per ton per mile, its sheer volume means the fifteen largest ships pollute as much as every car on Earth. Ship noise has also cut the North Atlantic right whale's acoustic habitat by up to 90 percent, disrupting communication essential for survival. The seafarers who bring us nearly everything deserve far more recognition, and the industry that carries our world deserves far more scrutiny.

## 32. THE FIRST-EVER CARGO SHIP POWERED BY GREEN FUEL | GREGORY HALVORSEN | TED

Interviewed about his company's goal to decarbonize its shipping business by 2040, Gregory Halvorsen explained that global logistics, ships, trucks, planes, and warehouses, account for 11 percent of all emissions, so the challenge is substantial. Over the past two years, his company ordered 25 container ships capable of running on green methanol, made from renewable electricity or sustainable biomass, with the first delivered just days before the interview. Three years ago, no such ships existed on order anywhere; today the industry has 120, evidence of the exponential shift needed. The bigger obstacle is scale: powering the company's entire 740-ship fleet on green methanol would require five to six percent of all wind and solar power produced worldwide. Rather than waiting a decade to pick a perfect solution among options like green ammonia, hydrogen, or nuclear power, Halvorsen argued the industry must act now, choosing methanol simply because it already works. Green fuel currently costs two to three times more than fossil fuel, but that increase dilutes through the supply chain, raising freight rates by 10 to 15 percent and adding only pennies to a typical consumer product; research suggests most goods could reach net-zero production for a one-to-four percent cost increase. To de-risk investment for fuel producers, the company has committed to long-term fuel purchase agreements, covering about 30 percent of its expected 2030 consumption, while working with customers willing to pay a modest green premium.

## 33. A NEW LIFELINE FOR THE WORLD'S CORAL REEFS | DR. SIENNA MARLOWE | TED

Coral reefs support more than a quarter of all marine life and sustain over a billion people, yet warming oceans are pushing them toward collapse. Heat-stressed coral polyps expel the algae that nourish them, causing bleaching; sustained heat kills them outright. We've already lost half the world's coral reefs, bleaching hit 53 countries in 2024, and up to 90 percent of corals could vanish by 2050. Having previously worked in medical research, I see a parallel: even without a cure, treatments can buy time, and reef restoration is that treatment. Traditional coral gardening, growing fragments in underwater nurseries before replanting them, has existed since the 1970s but is slow and hard to scale, producing fewer than 200,000 new corals worldwide each year. Over the past five years, hundreds of Australian scientists and engineers have developed automated methods to mass-produce heat-tolerant baby corals and deploy them using ceramic cradles, no longer requiring divers to plant each piece by hand. By targeting reefs most connected to others through ocean currents, restoring just three percent of Pacific coral could help drive recovery across half the entire ecosystem. Portable micronurseries will let coastal communities, like the Woppaburra man I know who says his "country is sick, country is crying," combine this technology with generations of traditional knowledge. By 2031 we aim to plant 1.2 million heat-tolerant corals a year, thirty times today's rate. The corals haven't given up, and neither should we.

## 34. HOW DO OCEAN CURRENTS WORK? | DR. NATALIE FERRIS

In 1992, a storm swept 28,000 rubber ducks and other bath toys from a cargo ship into the North Pacific; rather than staying together, they scattered worldwide, helping researchers map ocean currents. These currents are driven by wind, tides, changes in water density, and Earth's rotation, and fall into two categories: surface currents, which move the top 10 percent of ocean water, and deep-ocean currents, which move the rest. Near shore, tides and wind drive surface currents; in the open ocean, wind alone drags surface water along, with effects reaching depths of 400 meters. Earth's rotation bends these wind-driven currents into massive circular patterns called gyres, clockwise in the Northern Hemisphere and counterclockwise in the Southern, a phenomenon known as the Coriolis Effect, which also helps redistribute heat around the planet. Deep ocean currents work differently, driven by density: as water nears the poles, it grows colder and saltier, making it denser, so it sinks and sets warmer water in motion above it, a process called thermohaline circulation. Together, surface and deep currents form the Global Conveyor Belt, the longest current on Earth, which carries nutrients essential to ocean food chains but moves so slowly that a single drop of water can take a thousand years to complete the loop. Rising ocean temperatures now appear to be slowing this conveyor belt, with uncertain but potentially serious consequences for weather systems on both sides of the Atlantic.

## 35. CODING A BETTER GOVERNMENT | JENNIFER ALCOTT

A few years ago I started a program that persuades talented tech and design people to spend a year working inside city government, like a Peace Corps for programmers. One fellow in Boston noticed citizens were already shoveling snow from around fire hydrants, so he built an app letting residents "adopt" a hydrant, name it, and commit to digging it out, with the playful risk someone else could "steal" it if neglected. That small app spread virally: officials in other cities repurposed it for tsunami sirens, storm drains, and sidewalks, all without the years-long procurement process typical of government software, where one unrelated project cost taxpayers two billion dollars and still doesn't work. This reflects a broader shift: rather than treating government as a broken institution, a new generation treats it as a problem of collective action, something digital tools are very good at solving. Government, at its core, is simply what we do together that we can't do alone. When one Boston resident spotted an opossum in a neighbor's trash can through a public reporting app, another neighbor saw the post and quietly freed it, government having served merely as the platform connecting them, cheaper than dispatching animal control. Politics is just a thin layer atop the vast machinery of government we call bureaucracy, and if we want government to work for us, we need to engage with that machinery directly. The real question isn't just whether we raise our voices, but whether we're willing to lend our hands.

## 36. 3 WAYS TO UPGRADE DEMOCRACY FOR THE 21ST CENTURY | THOMAS OAKLEY

Ancient Athenians gathered ordinary citizens to make major political decisions together, a radical idea for its time despite excluding women and enslaved people. Nineteenth-century representative democracy was a similarly appropriate technology for an era when gathering everyone physically was impossible. Today, we're living through a crisis of representative democracy: countries from the UK to Hungary to New Zealand show signs of dysfunction, authoritarianism, or mass disengagement, largely because our democratic tools haven't been upgraded to match twenty-first-century expectations. What's needed is more everyday democracy, built on participation and genuine deliberation, high-quality discussion where people engage with evidence and each other rather than simply voting once every few years. Three real-world innovations point the way. Citizens' assemblies bring together a representative sample of the public, trained in respectful discussion and given expert evidence, to reach consensus recommendations; assemblies have shaped national mental health policy in Canada and a ten-year financial plan in Melbourne. Participatory budgeting lets residents directly allocate portions of public budgets through neighborhood-level discussions that scale up to city decisions; in Porto Alegre, Brazil, where it began, up to 50,000 people participate annually. Online consensus tools, like the platform Taiwan used to quickly craft regulations for ride-sharing services, use structured digital discussion to reach roughly 80 percent agreement within weeks. Each of these examples reflects a deeper faith: that people, given the right conditions, can handle complex decisions together remarkably well. As one philosopher put it, our best hope for good judgment isn't ourselves as individuals, it's each other.

## 37. WHY ORDINARY PEOPLE NEED TO UNDERSTAND POWER | DANIEL PRESCOTT

Civics sounds boring, but I believe we can make it compelling again by teaching it as the study of power, the capacity to make others act as you'd have them act. Power isn't inherently good or evil, like fire or physics, it just is, and governs every form of government. The trouble is that most people are profoundly illiterate about how it works: how a friendship quietly becomes a subsidy when officials become lobbyists, how a bias becomes policy, how a slogan becomes a movement. This illiteracy is often willful, some dismiss politics entirely, some trust data alone to fix imbalances, some believe power belongs solely to corporations or solely to government, and the resulting disengagement widens civic inequality, since the few who understand power happily fill the vacuum left by everyone else's ignorance. Civics ultimately asks one question: who decides? And no arena today offers a better place to practice answering it than the city. In Boulder, Colorado, citizen activists fought to municipalize their electric utility over the power company's resistance; at a major university, a long-dominant campus political group extended its influence into city school board elections. Power is flowing toward cities faster than ever, from bike-friendly street redesigns spreading worldwide to participatory budgeting spreading from Porto Alegre to New York and Chicago. I encourage everyone to write a narrative of their city's future, describing exactly how the change they want came to pass, because in learning to read power, we learn to write it.

## 38. A CRASH COURSE IN MAKING POLITICAL CHANGE | RACHEL OSWALT | TED

When the Flint water crisis unfolded, I was 27 and disillusioned, working in recycling, frustrated that Michigan's legislature seemed paralyzed by gerrymandering, politicians drawing voting districts to guarantee their own reelection. On a whim, I posted on Facebook asking if anyone wanted to help end it, and within hours thousands responded, none of us political professionals. We discovered Michigan's ballot initiative process let citizens amend the constitution directly, so we set out to write new language, gather signatures, and win a statewide vote. Volunteers brought unexpected skills: a woodcarver designed cheap signature-gathering clipboards for 33 cents apiece instead of eleven dollars; an engineer and former math teacher calculated how many volunteers we'd need. Rather than lobbying politicians who refused even to hold town halls, we held our own across the state, drawing crowds of Democrats, Republicans, and independents alike, who discovered they largely agreed on wanting a fairer process. We gathered over 442,000 signatures in 110 days, then watched 61 percent of voters approve the amendment in 2018, establishing an independent citizens' redistricting commission. That commission, thirteen ordinary residents chosen to reflect the state's demographics, ultimately drew Michigan's fairest maps ever, producing an exact match between votes cast and seats won in 2022. A year before that viral post, I'd written almost the same message and nobody responded; I'd felt alone and did nothing. You don't need a title or expertise to change your world, only the willingness to take one small step.

## 39. THE VALUE OF TRAVEL | HENRY DALTON | TEDXRAINIER

Having spent a third of my adult life on the road, I've come to see thoughtful travel as unquestionably worth its cost. Travel opens us to nature's wonder, whether hiking Alpine ridges or discovering, over a French shop counter, that cheese can be a passion, not just a sandwich filler. It also opens us to people: a small misunderstanding with an Italian boy who assumed Americans have "no teeth" because our bread is so soft became, once resolved, a reminder of how travel dissolves preconceptions. I grew up assuming the American dream sat atop the world; travel taught me every nation has its own, equally worth celebrating. An Afghan professor reminded me a third of the world eats with spoons, a third with chopsticks, a third with fingers, all equally civilized, a lesson I carried the rest of that trip. Travel also reveals pragmatic approaches to hard problems: countries that regulate sex work for safety rather than banning it, Scandinavian parents who supply supervised beer at graduation so teens won't drink and drive, Swiss cities offering clean needles and heroin clinics to cut disease and crime, and Portugal's decriminalization of all drugs, which found illegality itself was the real gateway to harder addiction. A Swiss friend explained his willingness to pay high taxes simply: what's it worth to live where there's no hunger, no homelessness? A whirling dervish in Turkey taught me people who seem utterly different are, underneath, fundamentally the same, perhaps travel's best souvenir.

## 40. LEARN TO TRAVEL -- TRAVEL TO LEARN | JASON MERRICK AT TEDXVANCOUVER

After surveying 1,732 people from 46 countries about their life's regrets, the single most common answer wasn't career or money, it was not having traveled more. My own journey began after a scooter accident broke my kneecap; the insurance settlement, just $20,000, funded a twelve-month, twenty-four-country trip around the world. Constant decision-making on the road, where to eat, sleep, sit, wear thin, and I learned to stop second-guessing choices after skipping an overnight bus in Rio de Janeiro that later collided head-on with a truck, killing six passengers, including the one sitting beside my friend. From then on, I trusted that wherever I was, I was meant to be. Across 107 countries, including places widely feared for kidnapping, unrest, or conflict, I've never been robbed, attacked, or seriously harmed, which taught me that most people would rather help a traveler than hurt one. My most reliable tools have simply been a genuine smile and trusting my gut instinct, the same instinct that, in hindsight, usually warns us before something goes wrong. The richest moments of travel rarely come from scenery alone but from the people met along the way: a philosophical Rasta elder in Jamaica, a farmer in Transylvania who taught me to dance with my heart, street children in Ethiopia who dreamed of the Olympics, some of whom made it. Whether crossing the world or exploring your own country, the same lesson applies: surround yourself with good people, trust your instincts, smile, and above all, don't panic.

## 41. THE DANGER OF A SINGLE STORY | AMARA OKAFOR | TED

I grew up in eastern Nigeria reading only British and American children's books, so as a young writer I created characters with blue eyes who played in snow and drank ginger beer, despite never having seen snow myself. Discovering African authors saved me from believing literature could only be about foreigners, and taught me that girls like me could exist in books too. As a child, my family employed a houseboy whose family my mother described only as poor; when his mother showed us a beautifully woven basket his brother had made, I was startled, because poverty had become the only story I knew about them. Years later, my American college roommate was similarly shocked I spoke English well and owned no "tribal music," her only story of Africa being one of catastrophe and pity. That single story traces back centuries, to European travelers who described African people in dehumanizing terms, and it persists today, as when a professor told me my novel wasn't "authentically African" simply because my characters weren't starving. I've been guilty of the same instinct myself, arriving in Mexico steeped in one-sided American narratives about immigration, and feeling ashamed to realize I'd reduced an entire people to a single storyline. Stereotypes aren't necessarily false, they're incomplete, and the danger lies in letting one story become the only story, which strips people of their full humanity. When we insist on hearing many stories instead of one, we regain something like paradise.

## 42. THE SECRET TO THRIVING RURAL COMMUNITIES | GRACE MONTOYA AT TEDXABQ

In a small mining town in New Mexico, a town clerk I'll call Christy secured funding for a new library, two police cars, and community center improvements, proving how much difference a single dedicated local can make. In Harding County, a returning resident I'll call Mary launched a youth entrepreneurship program and personally photographed and researched every vacant home in town, hoping to match them with new families. In a Navajo community on the state's west side, an organizer I'll call Margaret revived a blue corn farming project, pushed for broadband access, and built a telemedicine program after the local health clinic, which once saw 40,000 visits a year, shut its doors. New Mexico's rural communities face population decline, economic decline, and brain drain, yet they shape much of the state's culture, economy, and education, more than a quarter of the state's children attend rural schools. The people driving real change in these towns share three things: they were mentored by someone before them, they rarely receive financial support for what amounts to a second, unpaid job, and they need space to create without excessive outside regulation. If we invested more in mentorship, modest funding, and creative freedom for people like these, not just in rural areas but in the small communities that make up cities too, we could multiply their impact many times over.

## 43. HOW TO SOLVE TRAFFIC JAMS | ERIK LUNDQVIST

Road congestion plagues nearly every city on Earth, despite wildly different urban designs, and most attempted solutions try to dictate exactly what drivers should do instead. A better approach treats cities as complex, self-organizing systems, much like how no single authority manages a city's bread supply, yet it always somehow gets delivered. In my hometown of Stockholm, narrow old bridges created severe bottlenecks into the inner city, so planners introduced a modest congestion charge, just one or two euros, at these chokepoints. That small fee was enough to remove 20 percent of cars from rush hour, and because traffic congestion behaves nonlinearly, that modest reduction cut actual congestion dramatically. Introduced in 2006, then removed for a trial period before being reinstated in 2007, the charge produced a natural experiment: traffic surged back the very first day it was lifted, then dropped again just as sharply once reinstated. Even more surprising was public opinion: seventy percent of Stockholm residents initially opposed the charge, yet within a few years, seventy percent supported keeping it. Interviews revealed that most drivers who stopped commuting by car didn't even realize they'd changed their behavior, and most who changed their minds about the charge believed they'd supported it all along. This is the quiet power of a well-designed nudge: rather than telling people what to do, you shift the incentives slightly, and people adapt, embrace the change, and often come to like it, without ever noticing they've changed at all.

## 44. REDUCING THE VOLUME OF TRAFFIC JAMS | THEO ASANTE AT TEDXUNIVERSITYOFLEEDS

The average person spends roughly five years of their life stuck in traffic, sitting through the excessive accelerating and braking that harms both patience and the planet. Roughly 40 percent of car journeys carry just one person, rising to 70 percent for journeys with two, according to a European mobility think tank; if just 10 percent of commuters switched to scooters, 40 percent of traffic would vanish, and at 25 percent, congestion could disappear almost entirely. Reclaiming those five years could mean waking up half an hour later every single day for roughly 48 years, nearly an entire working life. The obstacle is that scooters and bikes lack the shelter, safety, and storage of a car. The solution may be vehicles that combine both: enclosed, gyroscopically stabilized two-wheeled electric vehicles already exist, seating up to two passengers, weaving through traffic like a bike while offering a car's protection from weather. With roughly 10 million car seats sitting empty on UK roads every day, according to one car-sharing service, more space-efficient vehicles could mean more space-efficient roads, potentially reducing the need for costly new infrastructure altogether. The road to that future isn't something we'll simply find; it's something we have to build, and in doing so, we might all finally get to sleep in a little more.

## 45. THE COUNTERINTUITIVE SECRET OF LEADERSHIP | VICTORIA HAMM | TED

Before every talk, I catch myself wishing conditions were different, a cooler room, a bigger stage, a more alert audience, the same coping mechanism many leaders fall into under pressure. But control outside ourselves is an illusion; the only thing we can manage is how we show up. In one demonstration, I stood silently on stage until an audience member told me to continue, a small act of surrender that created a new, co-created dynamic. Research I conducted with a business school analyzing 243 companies found adaptive cultures outperformed controlling ones threefold over three years. Surrender isn't passivity, it's accepting what's actually within your power. People don't change because of new processes; they act according to what they believe, and while you can't control someone's beliefs directly, you can create experiences that shift them. As a new HR executive tasked with leading layoffs at a technology company, I chose transparency over the usual secrecy, telling employees immediately that cuts were coming without knowing yet who or when. Some left for new jobs; those who stayed trusted the honesty enough to adapt, and the company ended up right-sizing itself without formal layoffs. At a struggling factory, a plant manager I'll call Tim, facing distrust and high injury rates, chainsawed down every "reserved for managers" sign in the lot, a small but powerful gesture that shifted trust and helped the plant become the company's best-performing site. Surrendering the illusion of control frees that energy for mastering how you actually respond and lead.

## 46. THE SECRET TO SUCCESSFULLY PITCHING AN IDEA | THE WAY WE WORK, A TED SERIES

The secret to a great pitch is FOMO, the fear of missing out. As someone who hears nearly 2,000 pitches a year, I've found that pitching, whether for a startup or a workplace project, is fundamentally storytelling: you need your audience to feel that saying no means missing something significant. First, know your audience. A venture capitalist cares about market size and big returns; a philanthropist cares about lasting social impact; a colleague may care about revenue, customer loyalty, or their own advancement, so frame your pitch around what matters to them specifically. Second, structure your pitch like a hero's journey in three acts: establish the current status quo, introduce the tension or problem existing solutions haven't solved, then present your idea as the hero swooping in to resolve it. One of the most compelling pitches I've heard opened with a startling fact, that a single gallon of milk can require roughly 1,000 gallons of water and significant carbon emissions to produce, before introducing a team of scientists who'd found a way to create dairy-like products from soybeans instead, sustainably and deliciously. Third, identify your weakest point, whether it's a missing team member, fierce competition, or an unproven idea, and address it directly rather than hoping no one notices. Owning your weaknesses openly builds more confidence than hiding them ever could. The best storytellers describe a believable future and show exactly how to get there, making all their audience needs to do is say yes.

## 47. HOW THE FOOD YOU EAT AFFECTS YOUR BRAIN | LILA FONTANE

If you dehydrated your brain and broke it down nutritionally, most of its weight would come from fats, with the rest made up of proteins, amino acids, micronutrients, and glucose, each shaping mood, energy, and mental function in distinct ways. Omega-3 and omega-6 fatty acids, found in nuts, seeds, and fatty fish, support brain cell membranes and help prevent degenerative conditions, while long-term consumption of trans and saturated fats may harm brain health. Proteins and amino acids supply the building blocks for neurotransmitters like dopamine and serotonin, which is part of why a pasta-heavy meal can leave you feeling calm while a protein-rich one leaves you alert; eating a varied diet helps keep these mood-regulating chemicals balanced. Antioxidant-rich fruits and vegetables help the brain fend off cell-damaging free radicals, while micronutrients like vitamins B6 and B12, along with trace minerals such as iron, zinc, and copper, are essential for cognitive development and long-term brain health. Though the brain makes up only about 2 percent of body weight, it consumes up to 20 percent of the body's energy, mostly from glucose, and the frontal lobes are so sensitive to blood sugar dips that mental fog is often an early sign of nutrient deficiency. High-glycemic foods like white bread cause a sharp glucose spike followed by a crash in attention and mood, while slower-digesting carbohydrates like oats and legumes provide steadier mental energy. What you eat has a direct, lasting effect on how your brain functions.

## 48. WHY DO COMPETITORS OPEN THEIR STORES NEXT TO ONE ANOTHER? | JAC DE HAAN

Why do gas stations, coffee shops, and grocery stores so often cluster together rather than spreading evenly across a town? A simple economic thought experiment called Hotelling's Model of Spatial Competition explains it. Imagine selling ice cream alone on a one-mile beach; placing your cart in the exact middle minimizes the walking distance for every customer. Now imagine a cousin arrives with an identical ice cream cart, and you agree to split the beach, each setting up a quarter mile from the center so no customer walks more than a quarter mile, a solution economists consider socially optimal. But that arrangement doesn't last: if your cousin moves toward the center to capture more customers, you're forced to move too, and this back-and-forth continues until you're both standing at the exact center of the beach, back to back, each still serving half the customers overall. At that point, neither of you can improve your position by moving further, a state economists call a Nash Equilibrium, but it's no longer optimal for customers, since people at either end of the beach now walk much farther than necessary. This same dynamic explains fast food chains, clothing stores, and phone kiosks clustering together at malls and intersections: customers might be better served by spread-out businesses, but each competitor is drawn toward staying as close to its rivals as possible.

## 49. THE STORY OF INDIAN CUISINE: TRADITION, INNOVATION, AND TASTE | CHEF ARJUN MENON | TEDXTKMCE

Indian cuisine has been shaped by wave after wave of outside influence, contrary to popular belief. The Aryan era brought flatbreads and stews cooked on charcoal; later invaders brought their own staples: Greeks may have introduced fenugreek, Persians brought charcoal kebabs and possibly the sweets we now call Indian, gulab jamun and jalebi actually trace back to Persia, and Mughal rule gave us biryani and the tandoor. The Portuguese introduced potatoes and chilies; before their arrival, Indian food wasn't spicy at all. Even idli, widely assumed to be South Indian, likely arrived through cultural exchange with Southeast Asia via steaming and fermentation techniques. Butter naan and butter chicken were actually refined in restaurants after independence and in the UK, softened and sweetened with butter and cream to suit milder British palates, while chicken à la Kiev, despite its name, was a Bengali chef's invention meant to impress British colonial guests. Today's progressive Indian cuisine continues that evolution, from filo-wrapped baked samosas to $14 plates of flavored pani puri water served abroad. Even dishes that sound outlandish, like soft drink-spiked instant noodles or Nutella biryani, echo how chocolate itself began as a savory Aztec dish before Europeans added sugar. Tomatoes and onions, now inseparable from Indian cooking, weren't native either; tomatoes arrived only after the seventeenth century, once considered poisonous in Europe. The lesson: comfort rarely produces growth. True progress, in cooking and in life, comes from stepping into discomfort and facing what unsettles us.

## 50. THE DEADLIEST THING IN YOUR KITCHEN | GEORGE HALSTEAD

Avocados sound harmless, yet slicing them incorrectly sent nearly 9,000 people to US emergency rooms in 2018, a phenomenon doctors now call "avocado hand." Knives aren't the biggest kitchen danger, though. Between 2011 and 2022, ovens and stove-oven combos were the deadliest kitchen appliances in the US, causing fatal fires and carbon monoxide leaks. Far more common than these sudden tragedies is the slow harm of everyday cooking-related air pollution, the fourth leading global cause of years of life lost. More than two billion people worldwide cook with solid fuels like wood or charcoal, whose incomplete combustion releases soot, carbon monoxide, and fine particulate matter that penetrates deep into the lungs and bloodstream; an estimated three million people die prematurely each year from illnesses linked to this exposure. Gas stoves burn cleaner than solid fuel but still release carbon monoxide, nitrogen oxides, and formaldehyde, and evidence links them to worsened asthma and higher asthma risk in children. Electric stoves pollute less, though no cooking method is entirely pollution-free, especially at high heat. Switching from gas to electric, particularly induction, along with proper ventilation, improves both indoor air quality and climate impact, since gas appliances release carbon dioxide and can leak methane, a far more potent greenhouse gas. Induction stoves also cook more efficiently, clean more easily, and won't burn you directly since they only heat magnetically responsive cookware. Some governments have begun banning new gas hookups and subsidizing the shift to electric. Just please, still cut your avocados properly.

## 51. COOKING AS ALCHEMY | ELIAS BRANDT + THEO CASTELLANO

When our restaurant opened in 2004, so many customers assumed it was Japanese and requested sushi rolls that we eventually printed the entire flavor profile of a maki roll onto edible paper, our first experiment in "flavor transformation." From there we escalated: photographing a seafood-and-champagne dish and serving the photo itself, tasting identical to the plate beside it; turning carrot cake into a frozen, hollow sphere resembling a floating planet; and disguising a Cuban pork sandwich as an actual cigar, spiced ash included, served in a dollar-store ashtray. We also reversed the trick, building "nachos" that were secretly dessert, candied chips, chocolate "beef," and shredded mango sorbet standing in for cheese, melting convincingly until the first bite revealed the illusion. Eventually we installed a full lab in our basement and asked, half-seriously, whether we could recreate a hamburger from exactly what a cow eats, corn, beets, and barley, without the cow; after a day of trial and error, we produced a plant-based patty that cooked, looked, and tasted remarkably like real beef. We also experimented with a natural berry protein that temporarily blocks sour taste receptors, turning a raw lemon sweet, and used it alongside seasoned, vacuum-sealed watermelon to create a convincing substitute for seared tuna. Finally, we challenged our staff to turn edible wild plants foraged around the city into a full menu, once even making a convincing barbecue sauce entirely from hay and crab apples, essentially free food that fooled every diner who tried it.

## 52. INTUITION IN THE KITCHEN | RENA APPLEBAUM | TEDXCAPEMAY

As a culinary nutrition educator, I cook intuitively, guided by mood, season, and craving rather than strict recipes, an approach that shapes how I teach others. Where I see an onion as fifty possible dishes, many people see only heartburn and watery eyes; how someone cooks reveals as much about them as what they eat. A third of Americans don't know how to cook, even as celebrity chefs and cooking shows multiply, and our waistlines and disease rates reflect that disconnect. For years I suffered an undiagnosed digestive condition, cycling through vegan, paleo, macrobiotic, and other extreme diets, each offering brief relief before symptoms returned, until I understood how deeply a stressed mind and stressed gut are connected. Training at a holistic culinary school taught me seven principles now central to how I teach: choose whole foods, favor traditional preparations like fermented foods that nourish gut bacteria, buy organic, seasonal, and local when possible, eat in colorful balance, and, above all, make it delicious, since even the healthiest meal goes uneaten if it isn't. To build real intuition in the kitchen, focus on ingredient quality, engage all your senses and taste constantly as you cook, visualize a dish before making it the way a dancer rehearses a performance, and cook without fear, since the energy we bring to food shapes how it tastes and nourishes us. Cooking is our most personal expression of love, and reclaiming that intuition is where real nourishment begins.

## 53. MILITARY ROBOTS AND THE FUTURE OF WAR | DR. MARCUS RAINE

In 2006, an American soldier died defusing a roadside bomb in Iraq; the commander's letter home noted, grimly, that at least "when a robot dies, you don't have to write a letter to its mother," since the "soldier" was a 42-pound bomb disposal robot. The US entered Iraq with a handful of drones and no ground robots; it now fields thousands of each, and one general predicted tens of thousands more, with computing power potentially a billion times greater within 25 years. This isn't a Hollywood robot uprising; it's a shift comparable to the atomic bomb, except unmanned systems change not just how wars are fought but who fights them, ending humanity's five-thousand-year monopoly on combat. America leads in military robotics, but 43 other countries are developing their own, and since much hardware is off-the-shelf, non-state actors have already used improvised drones, and jihadist websites have offered remote bomb detonation. Combat footage, often gathered by drones, now circulates online as what soldiers call "war porn," stripped of context and set to music. Drone pilots who fight twelve-hour shifts from Nevada and drive home report higher PTSD rates than many deployed units, and some worry psychological distance makes atrocities easier, "like a video game," as one pilot put it. Robots don't feel rage, but they also can't distinguish a grandmother in a wheelchair from a tank; our laws of war haven't caught up. Ultimately, the deeper question isn't whether our machines are built for war, but whether we are.

## 54. HOW DOES MATH GUIDE OUR SHIPS AT SEA? | ANDRE FONTAINE

Four hundred years ago, ocean navigation relied on "dead reckoning," estimating position from a ship's speed, direction, and time elapsed since leaving port, a method so imprecise that being off by just half a degree could mean sailing right past an island. Three inventions solved this. The sextant, developed by a London instrument maker, measured the angle between the sun and the horizon, which could be compared against the same angle recorded back home to calculate longitude. Clocks came next: in 1761, an English clockmaker built the first timepiece accurate enough to keep correct time despite a ship's pitching and rolling, though its handmade cost led many sailors to rely instead on cheaper, hours-long lunar calculations. The final piece came from an amateur Scottish mathematician who spent over twenty years developing logarithms to simplify these complex calculations, though his original system, based on awkward mathematical constants, was cumbersome. A mathematician from a London college later traveled unannounced to Scotland to suggest simplifying the system to a base of ten, giving us what we now call common logarithms, the standard tool for multiplication, division, and root calculations until electric calculators arrived in the twentieth century. Successful ocean navigation, in the end, depended on instrument makers, astronomers, mathematicians, and sailors all working across their separate fields, a reminder that real creativity often comes not from going deeper into one discipline alone, but from the cross-pollination between many.

## 55. WHAT MAKES A GOOD LIFE? LESSONS FROM THE LONGEST STUDY ON HAPPINESS | DR. STEPHEN MERCER | TED

A recent survey found over 80 percent of millennials named getting rich as a major life goal, and half named becoming famous, yet the longest-running study of adult life tells a different story. As the fourth director of a Harvard-based study that has tracked 724 men, and now their over 2,000 children, since 1938, following Harvard sophomores and boys from Boston's poorest neighborhoods, I can say the clearest lesson from 75 years of data isn't about wealth or achievement. It's that good relationships keep us happier and healthier, full stop. First, social connection matters enormously: people well connected to family, friends, and community are happier, physically healthier, and live longer, while loneliness, which over one in five Americans report at any time, is genuinely toxic to health and brain function. Second, it's not the number of relationships but their quality that counts; high-conflict marriages without warmth can be worse for health than divorce, while warm, secure relationships buffer us against pain, our most contentedly partnered participants stayed happy even on painful days, while those in unhappy relationships felt pain more intensely. Third, good relationships even protect memory: people in their eighties who felt they could count on a partner retained sharper memories longer, regardless of how much the couple bickered. Relationship satisfaction at fifty predicted healthy aging far better than midlife cholesterol levels did. The happiest retirees had actively replaced workmates with new friendships. As Mark Twain wrote, life is too brief for grudges; there's only time for loving.

## 56. THE POWER OF VULNERABILITY | DR. CLAIRE ASHFORD | TED

An event planner once asked how to describe me on a flyer, worried "researcher" sounded boring, so we settled on "storyteller," since I collect stories as data with a soul. Early in my career, a mentor insisted that if something can't be measured, it doesn't exist, and I set out to study connection, believing it could be neatly understood. Instead, I kept running into something unexpected: shame, the fear that some flaw makes us unworthy of connection, and beneath it, vulnerability, the willingness to be truly seen. Analyzing years of interviews, I found people with a strong sense of belonging shared one trait: they believed they were worthy of it. I called them "wholehearted," and what set them apart wasn't the absence of vulnerability but their willingness to lean into it, saying "I love you" first, investing in relationships with no guarantees. This upended my instinct to control and predict, triggering what my therapist called a spiritual awakening and I called a breakdown. I came to see we can't selectively numb painful emotions without also numbing joy and gratitude, which helps explain our heavily medicated, indebted, addicted society. We also numb vulnerability by manufacturing false certainty, in religion, politics, and blame, and by chasing perfection, especially in our children, when what they need is to hear they're imperfect, wired for struggle, and still worthy of love. Letting ourselves be seen, and believing we are enough, is what lets us stop screaming and start listening.

## 57. 3 STEPS TO TURN EVERYDAY GET-TOGETHERS INTO TRANSFORMATIVE GATHERINGS | DEVIKA RAO

Growing up shuttling between two very different households, an atheist, vegetarian family and an Evangelical Christian one, taught me early about navigating difference, shaping my career in conflict resolution. I noticed a gap between the energy of facilitated dialogues and the flatness of ordinary gatherings, where hosts obsess over food and flowers while leaving connection to chance. After interviewing dozens of skilled hosts, I found three principles for more meaningful gatherings. First, embrace a specific, even debatable purpose rather than a generic format. One expectant mother dreading a typical baby shower instead asked friends to design an evening addressing her fear of labor: friends shared stories reminding her of her own bravery and wove a symbolic bead necklace, she and her husband wrote new family vows, and guests brought favorite childhood memories instead of gifts. Second, cultivate good controversy rather than avoiding it. When an architecture firm couldn't agree whether to pivot toward design work, staging a theatrical "cage match" debate between two colleagues let people finally take a public stance and break their impasse. A tense family dinner might benefit similarly from banning opinions and asking for personal stories, a way into hard topics without burning the house down. Third, create pop-up rules, temporary shared norms for gatherings where guests don't share the same etiquette, like agreeing whoever checks their phone first pays the bill. As a child, I hid by becoming a chameleon between my two worlds; gatherings, done well, let us stop hiding and truly be seen.

## 58. THE POWER OF LITTLE CELEBRATIONS IN OUR LIVES | NOAH FISHER | TEDXYOUTH@LFNY

Reflecting on my own birthday, I realized we tend to dismiss small rituals like it as trivial, things we assume wouldn't matter if we skipped them, cake, balloons, a few messages from friends. But that assumption is wrong; we genuinely need these small things in our lives. It's easy to get overwhelmed chasing life's big milestones, school, college, career, marriage, a house, blindly pursuing the version of success we're told to want. In my experience, that's precisely when life starts to feel like a chore rather than something alive: the moment we lose touch with ourselves is the moment we forget the small things. Those small things look different for everyone, watching a favorite sport, greeting a neighbor in the elevator, spending time with friends, reading before bed, but what they share is the ability to make our lives distinctly our own. One statesman I admire once said that if every person created a tiny ripple of hope, those ripples together would have the power to change everything, and that's exactly the idea here: small gestures, combined, carry a strength that big achievements alone never will, because they don't just affect us, they ripple outward to everyone around us. Wishing someone a happy birthday, however small it seems, brightens their day just a little. So remember to notice the little things, and remember to send a small ripple of hope, to yourself and to the people around you.

## 59. HOW CULTURE DRIVES BEHAVIOURS | MARCEL DUBOIS | TEDXTRONDHEIM

Sitting in a square in Brussels, I answered a stranger who struck up conversation, then wondered why he'd spoken to me at all, a reaction revealing how much my Canadian upbringing had shifted after five years in Norway, where socializing follows far more structured norms. When you move to a new culture, you can confront it, complain about it in isolated expat bubbles, or conform, and only conforming lets you truly benefit from diversity. A wine tour guide in Catalonia once physically shook my tall, blond friend, mistaking his neutral expression, filtered through her own cultural lens, for disinterest; we all interpret behavior through cultural glasses. Years ago, I was barred from a leadership course reserved for women at a Scandinavian university, meant to fast-track women toward professorships in a field where fewer than 20 percent held that rank, an example of equality of results over equality of opportunity. Diverse boards, gender and culturally, notably outperform homogeneous ones. To help bridge these gaps, a friend and I began illustrating everyday cultural misunderstandings, work that's reached over a million people. Personal space varies dramatically by culture, leading to the familiar "dance" at conferences where one person steps closer and another steps back, neither realizing why they feel uncomfortable. Friendship itself is defined differently across cultures, from constant mutual presence to simply sitting comfortably in silence. Changing our cultural glasses, one step at a time, is how the world learns to benefit from difference.

## 60. THE SCIENCE OF VACATION | DEREK HOLLIS AT TEDXORLANDO

Cardiovascular disease is the world's leading cause of death, and while poor diet, inactivity, and smoking are well-known contributors, stress plays a major, underappreciated fourth role, constricting blood vessels and raising blood pressure. Partnering with a colleague from a psychology background, I found stress relief, like diet and exercise, is something people know they should pursue but often don't. One landmark study of over 12,000 middle-aged men found those who took regular annual vacations had a lower risk of heart attack and death. Our research identified a formula for maximizing a vacation's benefit. First, anticipation: the biggest happiness boost from a trip comes before it, not after, so booking early matters. Second, relaxation: vacationers who described their trip as relaxing reported happiness benefits lasting up to eight weeks, but this requires avoiding pitfalls like checking work email, which over 70 percent admit doing, and holding unrealistic expectations. Third, capitalization: sharing vacation stories and photos afterward, through storytelling or simply a bottle of wine with friends, helps cement positive memories. Despite this, most people don't use all their vacation days, whether from financial pressure, fear of falling behind, or believing "work is my life." My own wake-up call came after a suspected heart attack scare in an airport in 2007. My family's favorite vacation memory wasn't some exotic trip; it was two sons literally fighting in the mud on a hike in Hawaii. As the saying goes, a vacation is like love: anticipated with pleasure, experienced with discomfort, remembered with nostalgia.
"""

def estimate_syllables(word):
    word = word.lower().strip(".,!?:;\"'()[]")
    if not word: return 0
    # count vowel groups
    vowels = "aeiouy"
    count = 0
    prev_is_vowels = False
    for char in word:
        is_vowel = char in vowels
        if is_vowel and not prev_is_vowels:
            count += 1
        prev_is_vowels = is_vowel
    if word.endswith("e") and count > 1 and not word.endswith("le"):
        count -= 1
    return max(1, count)

# Parse raw text into 60 items
blocks = re.split(r'##\s*(\d+)\.\s*', raw_prompt_text)

raw_items = []
# blocks[0] is empty or header before '## 1.'
# then alternating: number, content
for i in range(1, len(blocks), 2):
    num = int(blocks[i])
    content = blocks[i+1].strip()
    
    lines = [l.strip() for l in content.split('\n') if l.strip()]
    title = lines[0]
    text = " ".join(lines[1:])
    
    raw_items.append({
        'orig_id': num,
        'title': title,
        'text': text
    })

print(f"Extracted {len(raw_items)} paragraphs.")

# Compute pronunciation / word complexity metrics for each paragraph
for item in raw_items:
    words = re.findall(r'\b[A-Za-z]+\b', item['text'])
    word_count = len(words)
    total_syllables = sum(estimate_syllables(w) for w in words)
    avg_syllables_per_word = total_syllables / max(1, word_count)
    
    # Complex words (3+ syllables)
    complex_words = [w for w in words if estimate_syllables(w) >= 3]
    pct_complex = len(complex_words) / max(1, word_count)
    
    avg_word_length = sum(len(w) for w in words) / max(1, word_count)
    
    # Combined Pronunciation Complexity Score
    # Multi-syllable density + complex word ratio + average word length
    complexity_score = (avg_syllables_per_word * 10) + (pct_complex * 20) + (avg_word_length * 2)
    
    item['word_count'] = word_count
    item['avg_syllables'] = round(avg_syllables_per_word, 2)
    item['pct_complex'] = round(pct_complex * 100, 1)
    item['avg_word_length'] = round(avg_word_length, 2)
    item['complexity_score'] = round(complexity_score, 2)

# Sort items by complexity_score ascending (most basic first, most advanced last)
sorted_items = sorted(raw_items, key=lambda x: x['complexity_score'])

print("\n--- Complexity Ranking Summary ---")
for idx, item in enumerate(sorted_items):
    level = "Basic" if idx < 20 else ("Intermediate" if idx < 40 else "Advanced")
    print(f"New ID {idx+1:02d} (Orig #{item['orig_id']:02d}) [{level:12s}] Score: {item['complexity_score']:5.2f} | AvgSyl: {item['avg_syllables']} | %Comp: {item['pct_complex']}% | Title: {item['title'][:45]}...")

# Construct final 60 items with IDs 1..60
final_60 = []
for idx, item in enumerate(sorted_items):
    new_id = idx + 1
    if new_id <= 20:
        level = "Basic"
    elif new_id <= 40:
        level = "Intermediate"
    else:
        level = "Advanced"
    
    # estimated reading time in seconds (~200 wpm)
    est_time = int(round((item['word_count'] / 200.0) * 60))
    
    # clean title formatting removing author and TED names
    clean_topic = item['title'].split(' | ')[0].strip()
    title_text = f"Paragraph {new_id} — {clean_topic}"
    
    final_60.append({
        "id": new_id,
        "title": title_text,
        "text": item['text'],
        "level": level,
        "estimatedReadingTime": est_time,
        "isCompleted": False,
        "maxAccuracy": 0
    })

# Save to app/src/main/assets/ted_paragraphs.json
out_path = "app/src/main/assets/ted_paragraphs.json"
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(final_60, f, indent=2, ensure_ascii=False)

print(f"\nSuccessfully created {out_path} with 60 items!")
